"""fix error in user table

Revision ID: dc70883e0110
Revises: c68b7a614fb7
Create Date: 2024-01-19 02:12:31.593113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc70883e0110'
down_revision: Union[str, None] = 'c68b7a614fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_fist_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_fist_name', 'user', ['first_name'], unique=False)
    # ### end Alembic commands ###
